name: Build & Deploy
run-name: Build & Deploy ${{ github.event.release.tag_name }}

on:
  release:
    types:
      - released

permissions:
  contents: read
  deployments: write

concurrency:
  group: "build-and-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repository
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install terser@5
          npm install html-minifier-terser@7
      - name: Replace {VERSION} with ${{ github.event.release.tag_name }}
        run: find repository/ \( -type d -name favicons -prune \) -o -type f -exec sed -i "s/{VERSION}/${{ github.event.release.tag_name }}/g" {} +
      - name: Minify website
        run: |
          npx html-minifier-terser --collapse-whitespace --remove-attribute-quotes --remove-comments --minify-js '{"module":true,"compress":{"global_defs":{"ADVANCED_OPTIONS_FILE":"a.js"}},"mangle":{"properties":{"regex":".*"}}}' --minify-css true --file-ext html --input-dir repository/ --output-dir _site/
          npx terser --module --compress --mangle --mangle-props 'regex=".*"' --output _site/a.js -- repository/advanced-options.mjs
      - name: Create manifest.webmanifest
        run: echo '{"name":"Private Secret Santa Generator","short_name":"Secret Santa","description":"Private Secret Santa generator with no email, no cookies, and no data sent to the server, with exclusions to prevent specific pairings.","start_url":".","display":"standalone","icons":[{"src":"favicon-192x192.png","sizes":"192x192","type":"image/png"},{"src":"favicon-512x512.png","sizes":"512x512","type":"image/png"}]}' > _site/manifest.webmanifest
      - name: Move favicons
        run: mv repository/favicons/* _site/
      - name: Move image
        run: mv repository/image.png _site/
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy _site/ --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }} --commit-message=${{ github.event.release.tag_name }}
